### ISSUE TITLE
Gradle issues

### ISSUE THREAD

**Issue by elect86** [LWJGLX/lwjgl3-awt#31] opened 2020-11-09 10:46 UTC
Hi,

I'm trying to import it in a gradle-based project

`implementation("org.lwjglx:lwjgl3-awt:0.1.7")`

but I keep getting

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not find lwjgl-opengl-3.2.3-natives-${platform}.jar (org.lwjgl:lwjgl-opengl:3.2.3).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-${platform}.jar
```

**Comment by tisoft** [comment] 2020-11-15 14:54
This is a duplicate of #25 I have posted a workaround there until the fixed version is released.

**Closed** 2021-01-03 13:36 UTC

**Comment by httpdigest** [comment] 2021-01-03 13:47
New release 0.1.8 will be up on Maven Central in a few minutes.
